[inputs.assets]
path = "assets/**/*"
output_path = "src/shared/assets"

[creator]
type = "group"
id = 160743627

[codegen]
output_name = "assets"
typescript = true
style = "nested"
strip_extension = true
