local assets = {
	images = {
		ui = {
			["alert_dismiss.png"] = "rbxassetid://75750956420119",
			["blur.png"] = "rbxassetid://137452805921848",
		},
	},
	sounds = {
		["button_down.ogg"] = "rbxassetid://136989481957343",
		["button_down_alt.ogg"] = "rbxassetid://137275715934825",
		["button_up.ogg"] = "rbxassetid://98094111604367",
		["button_up_alt.ogg"] = "rbxassetid://86428641824974",
		["alert_dismiss.ogg"] = "rbxassetid://100361050530547",
		["alert_neutral.ogg"] = "rbxassetid://125528144659633",
		["alert_money.ogg"] = "rbxassetid://70984826414868",
	},
}

return assets